-- AlterTable
ALTER TABLE `EventLot` ADD COLUMN `status` ENUM('ATIVO', 'INATIVO', 'ENCERRADO') NOT NULL DEFAULT 'INATIVO',
    ADD COLUMN `type` ENUM('PADRAO', 'PROMOCIONAL') NOT NULL DEFAULT 'PADRAO';
