const fs = require("fs");
const path = require("path");
const file = path.resolve("src/App.vue");
const text = fs.readFileSync(file, "utf8");
const target = `      <div\r\n        class="mx-auto flex min-h\[calc\(100vh-72px\)\] w-full max-w\[98%\] flex-col rounded-\[32px\] border border-\[color:var\(--app-shell-border\)\] bg-\[color:var\(--app-shell-bg\)\] px-4 py-10 shadow-\[0_45px_120px_-60px_rgba\(15,23,42,0.5\)\] backdrop-blur 2xl:max-w-\[1900px\] sm:px-6"\r\n      >\r\n        <main v-if="isAdminLayout" class="flex flex-1 gap-6 pb-6 min-h-\[calc\(100vh-72px\)\]">\r\n          <AdminSidebar :is-open="isSidebarOpen" :menu-items="adminMenuItems" @toggle="toggleSidebar" />\r\n          <div class="flex-1 rounded-\[28px\] bg-\[#F5F7FA\] p-4 sm:p-6">\r\n            <button\r\n              type="button"\r\n              class="mb-4 inline-flex items-center gap-2 rounded-full border border-\[#E4E7EC\] bg-white px-4 py-2 text-sm font-medium text-\[#1A1A1A\] shadow-sm transition hover:-translate-y-0.5 md:hidden"\r\n              @click="toggleSidebar"\r\n            >\r\n              <Bars3Icon class="h-5 w-5" aria-hidden="true" />\r\n              Menu\r\n            </button>\r\n            <RouterView />\r\n          </div>\r\n        </main>\r\n        <main v-else class="flex-1 pb-10">\r\n          <RouterView />\r\n        </main>\r\n\r\n        <footer\r\n          class="mt-auto border-t border-\[color:var\(--app-shell-border\)\] bg-\[color:var\(--surface-card-alt\)\] py-6 text-center text-sm text-\[color:var\(--text-muted\)\]"\r\n        >\r\n          &copy; {{ new Date().getFullYear() }} CATRE Ipitinga. Sistema de inscri????es e check-in.\r\n        </footer>\r\n      </div>`;
const replacement = `      <div v-if="isAdminLayout" class="min-h-[calc(100vh-72px)] w-full bg-[#f3f6ff] px-2 py-6 sm:px-6">\r\n        <div class="mx-auto flex min-h-[calc(100vh-72px)] w-full max-w-[1900px] gap-6">\r\n          <AdminSidebar :is-open="isSidebarOpen" :menu-items="adminMenuItems" @toggle="toggleSidebar" />\r\n          <div class="flex-1 rounded-[32px] border border-[color:var(--app-shell-border)] bg-white/95 px-4 py-6 shadow-2xl sm:px-8 sm:py-8">\r\n            <button\r\n              type="button"\r\n              class="mb-4 inline-flex items-center gap-2 rounded-full border border-[#E4E7EC] bg-white px-4 py-2 text-sm font-medium text-[#1A1A1A] shadow-sm transition hover:-translate-y-0.5 md:hidden"\r\n              @click="toggleSidebar"\r\n            >\r\n              <Bars3Icon class="h-5 w-5" aria-hidden="true" />\r\n              Menu\r\n            </button>\r\n            <RouterView />\r\n          </div>\r\n        </div>\r\n      </div>\r\n      <div\r\n        v-else\r\n        class="mx-auto flex min-h-[calc(100vh-72px)] w-full max-w-[98%] flex-col rounded-[32px] border border-[color:var(--app-shell-border)] bg-[color:var(--app-shell-bg)] px-4 py-10 shadow-[0_45px_120px_-60px_rgba(15,23,42,0.5)] backdrop-blur 2xl:max-w-[1900px] sm:px-6"\r\n      >\r\n        <main class="flex-1 pb-10">\r\n          <RouterView />\r\n        </main>\r\n\r\n        <footer\r\n          class="mt-auto border-t border-[color:var(--app-shell-border)] bg-[color:var(--surface-card-alt)] py-6 text-center text-sm text-[color:var(--text-muted)]"\r\n        >\r\n          &copy; {{ new Date().getFullYear() }} CATRE Ipitinga. Sistema de inscri????es e check-in.\r\n        </footer>\r\n      </div>`;
if (!text.includes(target)) {
  throw new Error('target not found');
}
const updated = text.replace(target, replacement);
fs.writeFileSync(file, updated);
